<?php
/** @var $message \App\Model\Eloquent\Message */
/** @var $user \App\Model\Eloquent\User */
/** @var Illuminate\Database\Eloquent\Collection $messages */
$user = $this->user;
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<style>
    .message { margin: 5px 0 0 5px; border: 1px solid grey; width: 450px; min-height: 100px;}
    .author { margin-left: 10px; }
    .text { padding-left: 15px; padding-top: 15px; }
    .date {color: grey; font-size: 11px;}
    .admin a { color: red; float: right; padding-right: 15px; }
    img { max-width: 100%; height: auto; display: block; }
</style>

<div class="user">
    <span><?= $user->getName()?> #<?=$user->getId()?></span>
<a href="/blog/logout/">Выйти</a><br>
</div>
<hr>


<?php $messages = $this->messages; ?>

<h2>Список сообщений:</h2>
<div class="messages" id="messages">
    <?php include 'messageList.phtml'; ?>
</div>

<input type="button" onclick="loadMessages(<?= (int) $this->last_id?>)" value="Показать ещё">

<hr>
Добавить сообщение
<form enctype="multipart/form-data" action="/blog/addMessage" method="post">
    <textarea style="width: 250px; height: 150px;" type="text" value="" name="text"></textarea><br><br>
    Изображение: <input type="file" name="image"><br>
    <input type="submit" value="Отправить">
</form>

<script>
    function loadMessages(lastId) {
        $.get(
            '/blog/loadList/?last_id=' + lastId,
            {},
            function (r) {
                var html = $('#messages').html();
                var newHtml = html + r;
                $('#messages').html(newHtml);
            }
        );
    }
</script>