<?php
/** @var $message \App\Model\Message */
/** @var $user \App\Model\User */
$user = $this->user;
?>
<style>
    .message { margin: 5px 0 0 5px; border: 1px solid grey; width: 450px; min-height: 100px;}
    .author { margin-left: 10px; }
    .text { padding-left: 15px; padding-top: 15px; }
    .date {color: grey; font-size: 11px;}
    .admin a { color: red; float: right; padding-right: 15px; }
    img { max-width: 100%; height: auto; display: block; }
</style>

<div class="user">
    <span><?= $user->getName()?></span>
<a href="/blog/logout/">Выйти</a><br>
</div>
<hr>
<h2>Список сообщений:</h2>

<?php if($messages = $this->messages): ?>
    <?php foreach ($messages as $message): ?>
        <div class="message">
            <? if($user->isAdmin()): ?>
                <div class="admin">
                    <a href="/admin/deleteMessage/?id=<?=$message->getId();?>">Удалить</a>
                </div>
            <? endif; ?>
            <span class="date"><?=$message->getCreatedAt();?> </span>
            <? if($author = $message->getAuthor()):?>
                <span class="author"><?=htmlspecialchars($author->getName());?></span>
            <? else: ?>
                <span class="author">Сообщение от удаленного пользователя</span>
            <? endif; ?>
            <div class="text"><?=htmlspecialchars(nl2br($message->getText()));?></div>
            <? if($message->getImage()):?>
                <div><img src="/images/<?=$message->getImage();?>" style="width: 150px;"></div>
            <? endif;?>
        </div>
    <?php endforeach; ?>
<?php else: ?>
<h3>Сообщений пока нет</h3>
<?php endif; ?>
<hr>
Добавить сообщение
<form enctype="multipart/form-data" action="/blog/addMessage" method="post">
    <textarea style="width: 250px; height: 150px;" type="text" value="" name="text"></textarea><br><br>
    Изображение: <input type="file" name="image"><br>
    <input type="submit" value="Отправить">
</form>