<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?=$this->title;?></title>
    <style>
        .block { display: inline-block; vertical-align: top; text-align: left; }
        .block input { width: 150px; }
        .field { width: 150px; display: inline-block; margin-bottom: 5px }
    </style>
</head>
<body>
<h3><?=$this->title;?></h3>
<?php
/** @var \App\Model\User $user */
$user = $this->user;
?>

<? if(!$user): ?>
    <div class="block" style="margin-left: 50px;">
        <h3>Войти</h3>
        <form action="/login/auth" method="post">
            <div class="field">Email:</div> <input type="text" value="" name="email"><br>
            <div class="field">Password:</div> <input type="text" value="" name="password"><br>
            <input type="submit" value="Войти">
        </form>

    </div>
    <h3><a href="/register">Я тут первый раз. Хочу зарегестрироваться</a></h3>
<? else: ?>
    Вы вошли как <?=$user->getName();?>
<? endif; ?>

</body>
</html>