<?php
/** @var \Illuminate\Database\Eloquent\Collection $users */
$users = $this->users;
/** @var \App\Model\Eloquent\User $user */
?>
<style>
    .user {
        display: flex;
        align-items: center;
    }
    .user__photo {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        overflow: hidden;
        border: 1px solid #c7ffcc;
        margin-right: 30px;
    }
    .user__photo img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
    .user__edit {
        display: block;
        color: #053a2b;
    }
    .user__delete {
        color:red;
    }
</style>
<?php if (!$users->isEmpty()) { ?>
    <?php foreach ($users as $user) { ?>
        <div class="user">
            <div class="user__photo">
                <img src="avatars/<?= $user->getImage() ?>" alt="<?= $user->getName() ?>">
            </div>
            <div class="user__fields">
                id пользователя #<b><?= $user->getId() ?></b><br>
                Имя пользователя: <b><?= $user->getName() ?></b><br>
                Email пользователя: <b><?= $user->getEmail() ?></b><br>
                <a href="/admin/editUser/?user_id=<?= $user->getId() ?>" class="user__edit">Редактировать пользователя</a>
                <a href="/admin/deleteUser/?user_id=<?= $user->getId() ?>" class="user__delete">Удалить пользователя</a>
            </div>
        </div>
        <br>
    <?php } ?>
<?php } ?>

